version: '3'

services:
  booking_db:
    container_name: booking
    image: postgres:14.1
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
